# Same for both models
[project]
device="cuda"
output_dim=6 
embedding_dim=300 
epoch_num=20

[data]
batch_size=32

# Hyperparameters for baseline
[model.baseline]
hidden_dim=256
lr=3e-4 # learning rate
wd=1e-5 # weight decay


# Hyperparameters for LSTM
[model.lstm]
hidden_dim=128
lr=3e-4
wd=1e-5

